# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-24 18:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_operations', '0002_auto_20180424_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='like_number',
        ),
    ]
