# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-19 17:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_emailverifyrecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailVerifyRecord',
        ),
    ]
