# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-20 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_delete_emailverifyrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(max_length=100, unique=True, verbose_name='邮箱地址'),
        ),
    ]
