# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-25 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20180420_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar_hash',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Gravatar头像'),
        ),
    ]
