# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-24 21:15
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='资源名称')),
                ('download_url', models.URLField(max_length=500, verbose_name='下载地址')),
                ('abstract', models.CharField(max_length=500, verbose_name='简介')),
                ('image', models.ImageField(default='default/sources/sources_01.jpg', max_length=500, upload_to='image/sources/%Y/%m', verbose_name='封面图')),
                ('description', models.TextField(verbose_name='详细介绍')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='修改时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='添加人')),
            ],
            options={
                'verbose_name': '资源',
                'verbose_name_plural': '资源',
            },
        ),
    ]
