# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-24 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sources',
            name='description_html',
            field=models.TextField(default='', verbose_name='详细介绍（html）'),
        ),
    ]
