# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-24 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0002_sources_description_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sources',
            name='description_html',
            field=models.TextField(blank=True, default='', null=True, verbose_name='详细介绍（html）'),
        ),
    ]
