# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-25 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0003_auto_20180424_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='sources',
            name='can_comment',
            field=models.BooleanField(default=True, verbose_name='能否评论'),
        ),
    ]
