# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-25 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0004_sources_can_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='sources',
            name='click_number',
            field=models.IntegerField(default=0, verbose_name='点击量'),
        ),
    ]
