# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-26 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0005_sources_click_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sources',
            name='image',
        ),
        migrations.AddField(
            model_name='sources',
            name='cover_url',
            field=models.URLField(default='media/default/sources/sources_01.jpg', max_length=500, verbose_name='封面图'),
        ),
    ]
