# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-26 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0006_auto_20180726_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sources',
            name='cover_url',
            field=models.URLField(default='http://pcgsvdl00.bkt.clouddn.com/default/sources/sources_01.jpg', max_length=500, verbose_name='封面图'),
        ),
    ]
