# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-11 12:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者'),
        ),
        migrations.AddField(
            model_name='articles',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.Series', verbose_name='文章系列'),
        ),
        migrations.AddField(
            model_name='articles',
            name='special_column',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.SpecialColumn', verbose_name='专栏'),
        ),
        migrations.AddField(
            model_name='articles',
            name='tags',
            field=models.ManyToManyField(to='articles.TagsOfArticle', verbose_name='文章标签'),
        ),
    ]
