# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-11 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20180411_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='content_html',
            field=models.TextField(blank=True, null=True, verbose_name='文章内容(html)'),
        ),
    ]
