# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-11 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20180411_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='tags',
            field=models.ManyToManyField(blank=True, to='articles.TagsOfArticle', verbose_name='文章标签'),
        ),
    ]
