# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-23 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_auto_20180423_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='image',
            field=models.ImageField(default='default/series/series_01.jpg', max_length=500, upload_to='image/series/%Y/%m', verbose_name='封面图'),
        ),
        migrations.AlterField(
            model_name='specialcolumn',
            name='image',
            field=models.ImageField(default='default/specialColumn/special_01.jpg', max_length=500, upload_to='image/specialColumn/%Y/%m', verbose_name='专栏封面'),
        ),
    ]
