# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-24 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_auto_20180423_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='favourite_number',
            field=models.IntegerField(default=0, verbose_name='收藏数'),
        ),
        migrations.AddField(
            model_name='articles',
            name='like_number',
            field=models.IntegerField(default=0, verbose_name='赞数'),
        ),
    ]
