# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-24 17:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_auto_20180424_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='favourite_number',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='like_number',
        ),
    ]
