# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-26 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_auto_20180424_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='cover_url',
            field=models.URLField(default='media/default/articles/article_01.jpg', max_length=500, verbose_name='封面图'),
        ),
    ]
