# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-26 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_articles_cover_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='image',
        ),
        migrations.RemoveField(
            model_name='series',
            name='image',
        ),
        migrations.RemoveField(
            model_name='specialcolumn',
            name='image',
        ),
        migrations.AddField(
            model_name='series',
            name='cover_url',
            field=models.URLField(default='media/default/series/series_01.jpg', max_length=500, verbose_name='封面图'),
        ),
        migrations.AddField(
            model_name='specialcolumn',
            name='cover_url',
            field=models.URLField(default='media/default/specialColumn/special_01.jpg', max_length=500, verbose_name='封面图'),
        ),
    ]
