# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-26 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_auto_20180726_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='cover_url',
            field=models.URLField(default='http://pcgsvdl00.bkt.clouddn.com/default/articles/article_01.jpg', max_length=500, verbose_name='封面图'),
        ),
        migrations.AlterField(
            model_name='series',
            name='cover_url',
            field=models.URLField(default='http://pcgsvdl00.bkt.clouddn.com/default/series/series_01.jpg', max_length=500, verbose_name='封面图'),
        ),
        migrations.AlterField(
            model_name='specialcolumn',
            name='cover_url',
            field=models.URLField(default='http://pcgsvdl00.bkt.clouddn.com/default/specialColumn/special_01.jpg', max_length=500, verbose_name='封面图'),
        ),
    ]
