# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-29 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_auto_20180726_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='cover_url',
            field=models.URLField(default='https://alpha-pics-1256464384.cos.ap-shanghai.myqcloud.com/default%2Farticles%2Farticle_01.jpg', max_length=500, verbose_name='封面图'),
        ),
        migrations.AlterField(
            model_name='series',
            name='cover_url',
            field=models.URLField(default='https://alpha-pics-1256464384.cos.ap-shanghai.myqcloud.com/default%2Fseries%2Fseries_01.jpg', max_length=500, verbose_name='封面图'),
        ),
        migrations.AlterField(
            model_name='specialcolumn',
            name='cover_url',
            field=models.URLField(default='https://alpha-pics-1256464384.cos.ap-shanghai.myqcloud.com/default%2FspecialColumn%2Fspecial_01.jpg ', max_length=500, verbose_name='封面图'),
        ),
    ]
